version: '2'
services:
  data:
    image: victormelnyk/data
    container_name: data
    stdin_open: true
    tty: true
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes_from:
      - data
    environment:
      - POSTGRES_PASSWORD=pgpass
      - PGDATA=/data/postgres
    depends_on:
      - data
  app:
    image: victormelnyk/test_app
    container_name: app
    ports:
      - "80:8080"
    links:
    - postgres
    depends_on:
      - data
      - postgres
  jenkins:
    image: jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
