version: '2'
services:
  jenkins:
    image: victormelnyk/jenkins
    container_name: jenkins
    ports:
      - 2013:8080   # web ui
      # - "50000:50000" # slave agent port
    volumes:
      - /data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
