version: '2'
services:
  postgres:
    image: postgres:9.6
    container_name: postgres-old
    ports:
      - 2012:5432
    volumes:
      - /data/postgresql/old:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pgpass
